### ISSUE TITLE
Allow cameras to wait for config server

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#290]
Cameras should wait for the config server to be up before trying to initialise. At the moment camera services throw errors if they are started up before the config server.

**Comment by wtgee** [comment]
@danjampro the `wait-for-it` scripts can be used for this, as in:

https://github.com/panoptes/POCS/blob/e41c2b1ae34188f91b0b7963886ebd541f876ea2/docker/docker-compose.yaml#L34-L37

It currently exists in the `panoptes-utils` repo and docker image. I will be stripping it out of repo soon, but installing via the system (i.e. `apt`) so it will be available `wait-for-it` instead of a full path.

**Comment by JAAlvarado-Montes** [comment]
@danjampro, wasn't this closed by #294 ?
