### ISSUE TITLE
Flat fields continue when it's too dark

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#302]
The flat fields should stop when it becomes too dark - we need to implement a second horizon in `POCS`.

**Comment by JAAlvarado-Montes** [comment]
I'd like to work on this @danjampro, but to add the new "`dark_horizon`" to `POCS` will have to wait because of the PR @wtgee is going to merge, right? Also, is it a second horizon completely necessary for this? I though flats are scheduled to be taken between certain times, so aren't we already checking (at least in theory) when it's too dark?
