### ISSUE TITLE
Autofocusing on all cameras doesn't start simultaneously 

### ISSUE THREAD

**Issue by Physarah** [wtgee/huntsman-pocs#503]
By the time jetson8 starts auto focusing, jetson0 has reached position 3/4. The same happens with flats

**Comment by danjampro** [comment]
This is because supposedly asynchronous calls to `take_exposure` and `autofocus_cameras` do not return immediately. The best solution is a redesign of the base code in POCS. In the mean time we could think about writing an asynchronous dispatcher, which would call e.g. `take_exposure` in a thread pool and return the corresponding events.
